services:
  db:
    image: postgres:15
    container_name: wordbook-db
    environment:
      POSTGRES_DB: wordbook_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
