spring.application.name=wordbook
# データベース接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/wordbook_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) の設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
